using System.Security.Cryptography;
using System.Text;
using George.Common;
using George.Data;
using ImageMagick;
using Microsoft.Extensions.Logging;

namespace George.Services
{
    /// <summary>
    /// On-the-fly product-image thumbnails with a disk cache. Originals are never modified - a resized
    /// JPEG copy is generated under {storage}/Thumbs/{width}/{sha1(relPath)}.jpg on first request and
    /// served straight from disk afterwards. Only meaningful for local file storage (the /files static
    /// mount); when the original cannot be resolved on disk the caller falls back to the original URL.
    /// </summary>
    public class ThumbnailService
    {
        /// <summary>Requested widths snap UP to the nearest entry so the cache stays bounded.</summary>
        public static readonly int[] AllowedWidths = { 96, 200, 400, 800, 1200 };

        /// <summary>Widths pre-generated by cache warming: table/list cells (96) and grid cards (400).</summary>
        public static readonly int[] WarmWidths = { 96, 400 };

        private static readonly string[] ImageExtensions = { ".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp" };

        private readonly ILogger<ThumbnailService> _logger;
        private readonly MediaStorage _mediaStorage;

        public ThumbnailService(ILogger<ThumbnailService> logger, MediaStorage mediaStorage)
        {
            _logger = logger;
            _mediaStorage = mediaStorage;
        }

        public static int SnapWidth(int width)
        {
            foreach (var w in AllowedWidths)
                if (w >= width) return w;
            return AllowedWidths[^1];
        }

        /// <summary>
        /// Resolves a public /files URL to the physical path of the original file. Returns null when the
        /// URL is not a /files URL, escapes the storage root (path traversal), has a non-image extension,
        /// or local storage is not configured. Does NOT check file existence.
        /// </summary>
        public static string? TryResolveOriginalPhysicalPath(string? src)
        {
            if (string.IsNullOrWhiteSpace(src)) return null;
            var basePath = SysConfig.Data.StorageLocalInternalBasePath;
            if (string.IsNullOrEmpty(basePath)) return null;
            if (!Uri.TryCreate(src.Trim(), UriKind.Absolute, out var uri)) return null;
            if (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps) return null;

            // The /files static mount serves StorageLocalInternalBasePath - take the path after /files/.
            var absPath = Uri.UnescapeDataString(uri.AbsolutePath);
            const string marker = "/files/";
            var idx = absPath.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
            if (idx < 0) return null;
            var rel = absPath[(idx + marker.Length)..].Replace('/', Path.DirectorySeparatorChar);
            if (string.IsNullOrWhiteSpace(rel)) return null;

            var ext = Path.GetExtension(rel);
            if (!ImageExtensions.Contains(ext, StringComparer.OrdinalIgnoreCase)) return null;

            var root = Path.GetFullPath(basePath);
            var full = Path.GetFullPath(Path.Combine(root, rel));
            if (!full.StartsWith(root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
                return null; // path traversal guard
            return full;
        }

        /// <summary>
        /// Returns the physical path of the cached thumbnail for (src, width), generating it on first
        /// call. Returns (null, false) when the original is not resolvable/existing on local storage.
        /// </summary>
        public async Task<(string? Path, bool Created)> GetOrCreateThumbAsync(string src, int width, CancellationToken cancelToken)
        {
            var original = TryResolveOriginalPhysicalPath(src);
            if (original == null || !File.Exists(original)) return (null, false);

            var w = SnapWidth(width);
            var root = Path.GetFullPath(SysConfig.Data.StorageLocalInternalBasePath!);
            var relKey = original.Substring(root.Length).TrimStart(Path.DirectorySeparatorChar);
            var hash = Convert.ToHexString(SHA1.HashData(Encoding.UTF8.GetBytes(relKey.ToLowerInvariant()))).ToLowerInvariant();
            var thumbDir = Path.Combine(root, "Thumbs", w.ToString());
            var thumbPath = Path.Combine(thumbDir, hash + ".jpg");
            // Freshness check: normal uploads mint a new GUID filename (new cache key), but a few flows
            // overwrite an existing file in place (e.g. deterministic woo-sync-*.jpg mirrors) - regenerate
            // when the original is newer than the cached thumb.
            if (File.Exists(thumbPath) && File.GetLastWriteTimeUtc(thumbPath) >= File.GetLastWriteTimeUtc(original))
                return (thumbPath, false);

            Directory.CreateDirectory(thumbDir);
            var bytes = await File.ReadAllBytesAsync(original, cancelToken);
            using var image = new MagickImage(bytes);
            image.AutoOrient(); // camera photos carry EXIF rotation; bake it in so the thumb is upright
            if (image.HasAlpha)
            {
                image.BackgroundColor = MagickColors.White;
                image.Alpha(AlphaOption.Remove);
            }
            if (image.Width > (uint)w)
                image.Resize((uint)w, 0); // height 0 = keep aspect ratio
            image.Format = MagickFormat.Jpeg;
            image.Quality = 85;

            // Write via temp + move so a concurrent request never reads a half-written file.
            var tmpPath = thumbPath + "." + Guid.NewGuid().ToString("N") + ".tmp";
            await File.WriteAllBytesAsync(tmpPath, image.ToByteArray(), cancelToken);
            File.Move(tmpPath, thumbPath, overwrite: true);
            return (thumbPath, true);
        }

        public class ThumbWarmResult
        {
            public int Urls { get; set; }
            public int Created { get; set; }
            public int AlreadyCached { get; set; }
            public int Unresolvable { get; set; }
            public int Failed { get; set; }
        }

        /// <summary>
        /// Pre-generates thumbnails for every product image URL in the system (canonical, per-site and
        /// variant images) at the given widths, so first paint never pays the resize cost. Idempotent -
        /// already-cached thumbs are skipped. Intended to run in the background (own DI scope).
        /// </summary>
        public async Task<ThumbWarmResult> WarmProductImageThumbsAsync(IReadOnlyCollection<int>? widths, CancellationToken cancelToken)
        {
            var widthList = (widths == null || widths.Count == 0) ? WarmWidths : widths.ToArray();
            var urls = await _mediaStorage.GetAllProductImageUrlsAsync(cancelToken);
            var res = new ThumbWarmResult { Urls = urls.Count };

            var done = 0;
            foreach (var url in urls)
            {
                foreach (var w in widthList)
                {
                    try
                    {
                        var (path, created) = await GetOrCreateThumbAsync(url, w, cancelToken);
                        if (path == null) res.Unresolvable++;
                        else if (created) res.Created++;
                        else res.AlreadyCached++;
                    }
                    catch (Exception ex)
                    {
                        res.Failed++;
                        _logger.LogWarning(ex, "Thumb warming failed for {Url} w={Width}", url, w);
                    }
                }
                done++;
                if (done % 200 == 0)
                    _logger.LogInformation("Thumb warming progress: {Done}/{Total} urls (created {Created}, cached {Cached}, failed {Failed})",
                        done, urls.Count, res.Created, res.AlreadyCached, res.Failed);
            }

            _logger.LogInformation("Thumb warming finished: {Total} urls, created {Created}, cached {Cached}, unresolvable {Unresolvable}, failed {Failed}",
                res.Urls, res.Created, res.AlreadyCached, res.Unresolvable, res.Failed);
            return res;
        }
    }
}
